#!/usr/bin/env python3
"""
Build script for Lammonsaato Pool Heating Optimizer

Creates a distribution package in dist/ containing all files needed
for Home Assistant deployment.

Usage:
    python scripts/build.py
    # or
    make build
"""

import os
import sys
import shutil
import json
import re
from datetime import datetime
from pathlib import Path


# Project root (parent of scripts/)
PROJECT_ROOT = Path(__file__).parent.parent
DIST_DIR = PROJECT_ROOT / "dist"


def load_env_file(env_path: Path) -> dict:
    """Load environment variables from .env file."""
    env_vars = {}
    if not env_path.exists():
        return env_vars

    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if '=' in line:
                key, value = line.split('=', 1)
                env_vars[key.strip()] = value.strip()
    return env_vars


def load_settings_env(settings_path: Path) -> dict:
    """Load Home Assistant settings from settings.env file."""
    return load_env_file(settings_path)


def clean_dist():
    """Remove existing dist directory."""
    if DIST_DIR.exists():
        print(f"Cleaning {DIST_DIR}...")
        shutil.rmtree(DIST_DIR)


def create_dist_structure():
    """Create dist directory structure matching HA config layout."""
    print("Creating distribution structure...")

    dirs = [
        DIST_DIR,
        DIST_DIR / "packages",
        DIST_DIR / "pyscript",
        DIST_DIR / "docs",
    ]

    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
        print(f"  Created {d.relative_to(PROJECT_ROOT)}")


def copy_ha_packages():
    """Copy Home Assistant package YAML files."""
    print("\nCopying HA packages...")

    src_dir = PROJECT_ROOT / "homeassistant" / "packages"
    dst_dir = DIST_DIR / "packages"

    for yaml_file in src_dir.glob("*.yaml"):
        shutil.copy2(yaml_file, dst_dir / yaml_file.name)
        print(f"  {yaml_file.name}")


def copy_pyscript_files():
    """Copy pyscript Python files."""
    print("\nCopying pyscript files...")

    src_dir = PROJECT_ROOT / "scripts" / "pyscript"
    dst_dir = DIST_DIR / "pyscript"

    for py_file in src_dir.glob("*.py"):
        shutil.copy2(py_file, dst_dir / py_file.name)
        print(f"  {py_file.name}")


def generate_secrets_yaml():
    """Generate secrets.yaml with values from .env file."""
    print("\nGenerating secrets.yaml...")

    env_vars = load_env_file(PROJECT_ROOT / ".env")

    # Map .env variables to secrets.yaml keys
    secrets = {
        'thermia_host': env_vars.get('THERMIA_HOST', '192.168.X.X'),
        'thermia_port': env_vars.get('THERMIA_PORT', '502'),
        'firebase_url': env_vars.get('FIREBASE_URL', 'https://your-project.firebaseio.com'),
    }

    # Build secrets.yaml content
    content = """# Lammonsaato Secrets
# Generated by build script - review values before deployment

# Thermia Heat Pump Modbus Connection
thermia_host: "{thermia_host}"
thermia_port: {thermia_port}

# Firebase Configuration (optional - for external data logging)
firebase_url: "{firebase_url}"
""".format(**secrets)

    secrets_file = DIST_DIR / "secrets.yaml"
    secrets_file.write_text(content)
    print(f"  secrets.yaml (thermia: {secrets['thermia_host']}:{secrets['thermia_port']})")


def copy_firebase_credentials():
    """Firebase disabled - using local logging instead."""
    print("\n(Firebase disabled - using local file logging)")


def copy_config_templates():
    """Copy configuration templates."""
    print("\nCopying config templates...")

    src_dir = PROJECT_ROOT / "config"
    dst_dir = DIST_DIR

    if not src_dir.exists():
        print("  (no config templates found)")
        return

    for template in src_dir.glob("*.template"):
        shutil.copy2(template, dst_dir / template.name)
        print(f"  {template.name}")


def copy_documentation():
    """Copy essential documentation."""
    print("\nCopying documentation...")

    docs_to_copy = [
        "docs/SETUP_GUIDE.md",
        "docs/TROUBLESHOOTING.md",
        "docs/THERMIA_REGISTERS.md",
    ]

    for doc_path in docs_to_copy:
        src = PROJECT_ROOT / doc_path
        if src.exists():
            dst = DIST_DIR / "docs" / src.name
            shutil.copy2(src, dst)
            print(f"  {src.name}")


def create_install_script():
    """Create an installation helper script."""
    print("\nCreating install script...")

    install_script = DIST_DIR / "install.sh"
    install_script.write_text("""\
#!/bin/bash
# Lammonsaato Installation Script
# Run this on your Home Assistant host

set -e

HA_CONFIG="${HA_CONFIG:-/config}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Installing Lammonsaato Pool Heating Optimizer"
echo "=============================================="
echo ""

# Check if running on Home Assistant
if [ ! -d "$HA_CONFIG" ]; then
    echo "Error: Home Assistant config directory not found at $HA_CONFIG"
    echo "Set HA_CONFIG environment variable to your config path"
    exit 1
fi

# Create directories
echo "Creating directories..."
mkdir -p "$HA_CONFIG/packages"
mkdir -p "$HA_CONFIG/pyscript"
mkdir -p "$HA_CONFIG/pool_heating_logs"

# Copy packages
echo ""
echo "Installing packages..."
cp -v "$SCRIPT_DIR/packages/"*.yaml "$HA_CONFIG/packages/"

# Copy pyscript
echo ""
echo "Installing pyscript modules..."
cp -v "$SCRIPT_DIR/pyscript/"*.py "$HA_CONFIG/pyscript/"

# Handle secrets.yaml
echo ""
if [ -f "$SCRIPT_DIR/secrets.yaml" ]; then
    if [ -f "$HA_CONFIG/secrets.yaml" ]; then
        echo "Existing secrets.yaml found - merging..."
        echo ""
        echo "Add these lines to your $HA_CONFIG/secrets.yaml:"
        echo "----------------------------------------"
        cat "$SCRIPT_DIR/secrets.yaml"
        echo "----------------------------------------"
        echo ""
        echo "Backup your secrets.yaml and add the above entries manually."
    else
        echo "Installing secrets.yaml..."
        cp -v "$SCRIPT_DIR/secrets.yaml" "$HA_CONFIG/secrets.yaml"
    fi
fi

# Verify configuration.yaml has packages enabled
echo ""
echo "Checking configuration.yaml for packages support..."
if grep -q "packages:" "$HA_CONFIG/configuration.yaml" 2>/dev/null; then
    echo "  ✓ packages already configured"
else
    echo "  ! Add the following to your configuration.yaml:"
    echo ""
    echo "    homeassistant:"
    echo "      packages: !include_dir_named packages"
    echo ""
fi

# Check for pyscript configuration
if grep -q "pyscript:" "$HA_CONFIG/configuration.yaml" 2>/dev/null; then
    echo "  ✓ pyscript already configured"
else
    echo "  ! Add the following to your configuration.yaml:"
    echo ""
    echo "    pyscript:"
    echo "      allow_all_imports: true"
    echo "      hass_is_global: true"
    echo ""
fi

echo ""
echo "=============================================="
echo "Installation complete!"
echo "=============================================="
echo ""
echo "Final steps:"
echo "1. Verify/merge secrets.yaml entries"
echo "2. Ensure packages and pyscript are enabled in configuration.yaml"
echo "3. Restart Home Assistant: Settings > System > Restart"
echo ""
echo "After restart, verify installation:"
echo "  - Check Settings > System > Logs for errors"
echo "  - Check Developer Tools > States for pool_heating entities"
echo ""
echo "To test logging:"
echo "  Developer Tools > Services > pyscript.test_logging"
echo "  Logs stored in: /config/pool_heating_logs/"
echo ""
echo "See docs/SETUP_GUIDE.md for detailed instructions"
""")
    install_script.chmod(0o755)
    print("  install.sh")


def create_manifest():
    """Create a manifest file with build info."""
    print("\nCreating manifest...")

    # Get version from git if available
    version = "dev"
    try:
        import subprocess
        result = subprocess.run(
            ["git", "describe", "--tags", "--always"],
            capture_output=True, text=True, cwd=PROJECT_ROOT
        )
        if result.returncode == 0:
            version = result.stdout.strip()
    except Exception:
        pass

    # Get git commit
    commit = "unknown"
    try:
        import subprocess
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, cwd=PROJECT_ROOT
        )
        if result.returncode == 0:
            commit = result.stdout.strip()
    except Exception:
        pass

    manifest = {
        "name": "lammonsaato",
        "description": "Pool Heating Optimizer for Home Assistant",
        "version": version,
        "commit": commit,
        "build_date": datetime.now().isoformat(),
        "files": {
            "packages": list(str(f.name) for f in (DIST_DIR / "packages").glob("*")),
            "pyscript": list(str(f.name) for f in (DIST_DIR / "pyscript").glob("*")),
            "docs": list(str(f.name) for f in (DIST_DIR / "docs").glob("*")),
        },
        "requirements": {
            "home_assistant": "2023.1+",
            "integrations": [
                "nordpool (via HACS)",
                "pyscript (via HACS)",
                "shelly",
            ],
            "optional": [
                "modbus (for Thermia)",
                "firebase (for data export)",
            ]
        }
    }

    manifest_path = DIST_DIR / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2))
    print(f"  manifest.json (version: {version})")


def create_readme():
    """Create a README for the dist package."""
    print("\nCreating README...")

    readme = DIST_DIR / "README.md"
    readme.write_text("""\
# Lammonsaato - Pool Heating Optimizer

Pre-configured distribution package for Home Assistant deployment.

This package is pre-configured with your environment settings. Minimal changes
needed after deployment.

## Quick Install

**Option 1: Using install script (recommended)**
```bash
# Copy entire dist folder to Home Assistant
scp -r . root@homeassistant.local:/tmp/lammonsaato/

# SSH in and run install script
ssh root@homeassistant.local
cd /tmp/lammonsaato
./install.sh
```

**Option 2: Direct copy**
```bash
# Copy directly to config directory
scp -r packages pyscript secrets.yaml root@homeassistant.local:/config/
```

**Option 3: Manual copy via File Editor/Samba**
1. Copy `packages/` folder to `/config/packages/`
2. Copy `pyscript/` folder to `/config/pyscript/`
3. Merge `secrets.yaml` entries into your existing `/config/secrets.yaml`

## After Installation

1. **Add to configuration.yaml** (if not already present):
   ```yaml
   homeassistant:
     packages: !include_dir_named packages

   pyscript:
     allow_all_imports: true
     hass_is_global: true
   ```

2. **Restart Home Assistant**: Settings > System > Restart

3. **Verify installation**:
   - Check Settings > System > Logs for errors
   - Check Developer Tools > States for `input_boolean.pool_heating_enabled`

4. **Enable**: Turn on `input_boolean.pool_heating_enabled` in Helpers

## Package Contents

```
dist/
├── packages/
│   └── pool_heating.yaml    # Main HA configuration
├── pyscript/
│   ├── pool_heating.py      # Price optimization algorithm
│   └── firebase_sync.py     # Optional: Firebase logging
├── secrets.yaml             # Pre-configured secrets
├── install.sh               # Installation script
└── docs/                    # Documentation
```

## Pre-configured Settings

This package includes:
- **Thermia Modbus**: Configured from .env
- **Firebase URL**: Configured from .env
- **Shelly Switches**:
  - `switch.altaan_lammityksen_esto` (heating prevention)
  - `switch.altaan_kiertovesipumppu` (circulation pump)

## How It Works

The system optimizes pool heating using 15-minute Nordpool price intervals:

1. Fetches tomorrow's prices (~13:00 CET)
2. Schedules 2 hours of heating during cheapest night hours (21:00-07:00)
3. Uses 30-45 minute heating blocks with equal breaks
4. Controls pool heating via two Shelly switches

## Support

See `docs/SETUP_GUIDE.md` for detailed instructions and troubleshooting.
""")
    print("  README.md")


def print_summary():
    """Print build summary."""
    print("\n" + "=" * 60)
    print("BUILD COMPLETE")
    print("=" * 60)

    # Count files
    total_files = 0
    for root, dirs, files in os.walk(DIST_DIR):
        total_files += len(files)

    # Calculate size
    total_size = sum(
        f.stat().st_size
        for f in DIST_DIR.rglob("*")
        if f.is_file()
    )

    print(f"\nOutput: {DIST_DIR.relative_to(PROJECT_ROOT)}/")
    print(f"Files:  {total_files}")
    print(f"Size:   {total_size / 1024:.1f} KB")

    print("\nContents:")
    for item in sorted(DIST_DIR.iterdir()):
        if item.is_dir():
            count = len(list(item.glob("*")))
            print(f"  {item.name}/  ({count} files)")
        else:
            print(f"  {item.name}")

    print("\nTo deploy:")
    print(f"  scp -r {DIST_DIR.relative_to(PROJECT_ROOT)}/* user@homeassistant:/config/")
    print("  # or run install.sh on the HA host")


def main():
    """Main build process."""
    print("Lammonsaato Build Script")
    print("=" * 60)
    print(f"Project root: {PROJECT_ROOT}")
    print(f"Output dir:   {DIST_DIR}")
    print("")

    # Check for .env file
    env_file = PROJECT_ROOT / ".env"
    if env_file.exists():
        print(f"Using config from: {env_file}")
    else:
        print("Warning: No .env file found - using default values")
    print("")

    # Build steps
    clean_dist()
    create_dist_structure()
    copy_ha_packages()
    copy_pyscript_files()
    generate_secrets_yaml()
    copy_firebase_credentials()
    copy_config_templates()
    copy_documentation()
    create_install_script()
    create_manifest()
    create_readme()
    print_summary()

    return 0


if __name__ == "__main__":
    sys.exit(main())
